### PR TITLE
Use solve_ivp without the py-pde wrapper, but retain fields and grids from py-pde, for more readable code

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
Given [the arguments from this closed discussion](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/discussions/26#discussioncomment-10535420), I think we should proceed with the methodology from the `Use_solve_ivp_without_py-pde_wrapper_branch` and merge it into `main` _to include this into our release_.

In summary, the `Use solve ivp without py pde wrapper` branch offers these features:

- Faster integrations than `main` branch.
- Allows for all features of `solve_ivp`, such as a Jacobian sparsity matrix
- Event tracking has been implemented, for a number of fields and derived quantities, i.e. the times of sign changes are recorded.

while the unique features of the `main` branch are less important to us.

### CODE REVIEW

**Comment by HannoSpreeuw** [comment]
I am currently looking at issue #43 , which is about documentation. 

Last bullet: `saving U at the bottom`, this feature will **vanish in the merge**.

In `main` it is currently implemented through
```
    if tracker_parms["track_U_at_bottom"]:
        data_tracker = DataTracker(eq.track_U_at_bottom, \
                               interval = tracker_parms["data_tracker_interval"])
```
and 
```
    sol, info = eq.solve(state, **solver_parms, tracker=["progress", \
                         storage.tracker(\
                             tracker_parms["progress_tracker_interval"]),\
                         live_plots, data_tracker])
``` 

without the `py-pde` wrapper of `solve_ivp` we can no longer apply the `DataTracker` class and tracking of `U at the bottom` will have to be implemented differently.                         

@EmiliaJarochowska  Pls let me know if _tracking (and saving) U at the bottom_ has to be readded.

**Comment by HannoSpreeuw** [comment]
> @EmiliaJarochowska Pls let me know if _tracking (and saving) U at the bottom_ has to be readded.

After discussion: will not be readded anytime soon, instead a similar feature in rhythmite will be deployed.

**Comment by EmiliaJarochowska** [comment]
FYI I managed to crash it:
```
/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/radau.py:401: RuntimeWarning: underflow encountered in nextafter
  min_step = 10 * np.abs(np.nextafter(t, self.direction * np.inf) - t)
 26%|█████████                          | 25866/100000 [03:56<07:03, 174.89it/s]/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/radau.py:118: RuntimeWarning: underflow encountered in divide
  dW_norm = norm(dW / scale)
```
by setting Phi0 to 0.9, Phi00 to 0.8, and b to 2.66667. 
However, this also crashed the `main` so we knew it was prone to it. 
So I suggest leaving it like this.

Otherwise works and is indeed very fast.

But the number of solver options and their implications for the numerical methods strengthens the argument that some additional documentation is needed. I will continue this discussion in the respective issue.

**Review by EmiliaJarochowska — APPROVED** [review]
Pylint highlights some minor issues here and there but the code works so I'll merge now.

**Comment by EmiliaJarochowska** [comment]
I interrupted that run but here are the errors:
```
  File "/Users/emilia/Documents/Documents - UU101746/GitHub/Integrating-diagenetic-equations-using-Python/marlpde/Evolve_scenario.py", line 211, in <module>
    Plot_results(*integrate_equations(solver_parms, tracker_parms, pde_parms))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilia/Documents/Documents - UU101746/GitHub/Integrating-diagenetic-equations-using-Python/marlpde/Evolve_scenario.py", line 104, in integrate_equations
    sol = solve_ivp(eq.fun if backend=="numpy" else eq.fun_numba, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/ivp.py", line 591, in solve_ivp
    message = solver.step()
              ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/base.py", line 181, in step
    success, message = self._step_impl()
                       ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/radau.py", line 504, in _step_impl
    f_new = self.fun(t_new, y_new)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/base.py", line 136, in fun
    def fun(t, y):
```

**Comment by HannoSpreeuw** [comment]
> FYI I managed to crash it:
> 
> ```
> /opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/radau.py:401: RuntimeWarning: underflow encountered in nextafter
>   min_step = 10 * np.abs(np.nextafter(t, self.direction * np.inf) - t)
>  26%|█████████                          | 25866/100000 [03:56<07:03, 174.89it/s]/opt/homebrew/lib/python3.11/site-packages/scipy/integrate/_ivp/radau.py:118: RuntimeWarning: underflow encountered in divide
>   dW_norm = norm(dW / scale)
> ```
> 
> by setting Phi0 to 0.9, Phi00 to 0.8, and b to 2.66667. However, this also crashed the `main` so we knew it was prone to it. So I suggest leaving it like this.
> 
> Otherwise works and is indeed very fast.
> 
> But the number of solver options and their implications for the numerical methods strengthens the argument that some additional documentation is needed. I will continue this discussion in the respective issue.

Yes, I think we discussed those cases as part of issue #36 .

**Comment by HannoSpreeuw** [comment]
Btw, you shared the warning, was there also a crash?

We do not want marlpde to crash on very small time steps, so that is why we have **under="warn"**
in [np.seterr(divide="raise", over="raise", under="warn", invalid="raise")](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/blob/0c65692dd53ded15dabbb558af07410cd6876752/marlpde/LHeureux_model.py#L6C1-L6C71).

**Comment by EmiliaJarochowska** [comment]
I am not sure if it crashed, it got stuck at 26% and didn't move, just displayed the warning. Shall I re-try?

**Comment by HannoSpreeuw** [comment]
Yes, please retry, I'd be surprised if it really halted.

**Comment by EmiliaJarochowska** [comment]
It didn't crash, just stuck at 26%. Been at 26% for > 1 h now without any progress. But again, this is a crash case.

**Comment by HannoSpreeuw** [comment]
Okay, this is something [we do not want to solve](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/issues/36#issuecomment-2247394167), let's leave it.

**Comment by EmiliaJarochowska** [comment]
Oh, now I discovered that it actually finished. But with the following:
```
Status = -1 

Success = False 
```
and
```
Message from solve_ivp = Required step size is less than spacing between numbers. 
```
but yes, it's not to be fixed.

**Pull request merged**
