### PR TITLE
Save metadata

### LINKED ISSUE #19: Propagate Solver and Scenario parameters into output hdf5 file
Currently, the only label the output hdf5 files have is the datetime of the file name.

The information about the input parameters defined in [parameters.py](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/blob/Cleanup_from_linting/marlpde/parameters.py) is lost. 

hdf5 provides for keys and using those keys we can retain the input parameters.

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
This simple addition `info=kwargs` is enough to save metadata.

To read the attributes added to the hdf5 file written in this way, run something like 
```
import h5py
hf =h5py.File("file_just_created.h5", "r"); 
hf.attrs.keys()
```
Btw, `hf.keys()` will give you the names of the datasets saved in `file_just_created.h5`.

Fixes #19

### CODE REVIEW

**Review by EmiliaJarochowska — APPROVED** [review]
So what I learned from this is to next time think before I submit an issue so I don't waste @HannoSpreeuw's time 😞

The data needed to compute the saturation had been already saved before (for calcite), corresponding to `sol.data[2]` and `sol.data[3]`. The `info` option of `FileStorage` saves metadata to the hdf5 file, but the concentrations had been there already...

**However, this PR resolves half of #19!** Because now we have scenario parameters stored in the output file. Solver parameters are missing, otherwise this would close a different issue. So not a wasted time after all.

**Comment by HannoSpreeuw** [comment]
Are the solver parameters really missing? 
We have
```
storage = FileStorage(stored_results, info=kwargs)
```
and `kwargs` also includes solver parameters.

**Comment by EmiliaJarochowska** [comment]
Oh, sorry. Yes, all parameters from `kwargs` are saved. I thought solver parameters would also include things like `solver="explicit", scheme = "rk", adaptive = True` etc. 
So I should close #19 ?

**Comment by HannoSpreeuw** [comment]
Yeah, o now I see what you mean. Yes, this only includes the parameters from the parameters.Solver dataclass.
So good point!
How about me adding arguments like the ones you mentioned, i.e. `solver="explicit", scheme = "rk", adaptive = True` to the Solver dataclass?

**Comment by EmiliaJarochowska** [comment]
I don't know to what extent we were going to change these arguments in the future. I still have in mind what Karline suggested (and seems in line with many textbooks) that implicit solvers would be more appropriate for our case. So if we are going to do runs with different solvers, it would be worth adding. But then you'd probably have to consider the whole range of parameters different solvers can take, as in https://py-pde.readthedocs.io/en/latest/packages/pde.solvers.html ?

**Comment by HannoSpreeuw** [comment]
Yes, but it seems fine to accommodate for all these solvers and beyond, i.e. `solve_ivp` without the py-pde wrapper, which gives more options, such as a functional Jacobian, see the `Use_solve_ivp_without_py-pde_wrapper` branch.

To control this through the parameters.Solver dataclass is indeed the most elegant solution.
I just published a commit to provide for this.

**Pull request merged**
