### PR TITLE
Oscillations like fortran

### LINKED ISSUE #39: Reproduce oscillations caused by a typo in Eq 25 in the Fortran code
Charlotte discovered that [correcting a typo in the Fortran code](https://github.com/astro-turing/lheureux/commit/f3c67ecbe0f287835f44da295366618bb9b4daf7) to what was stated in the paper brought the oscillations back. After applying the typo, Fortran and rhytmite reproduce oscillations again. Try to reproduce them also with marlpde.

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
Fixes #39 and #40.

The 'typo' is not included here, any manipulation of the porosity diffusion coefficient should be done by modifying `b`.
However, `b` is set here to a default value of 5e-4, not to the [rhythmite value](https://github.com/cedrict/rhythmite/blob/6cd2e28f958857a3f0bf8a20320012af54277bfe/DiagenesisModel.py#L107). I.e. after merging with `main` and then running, marlpde will not yield oscillations within 250 ka.

Initial and surface porosity are both set to 0.8, i.e. different from Scenario A.

There is an [ongoing discussion on how to apply the FV scheme](https://github.com/cedrict/rhythmite/discussions/6). It would be neat to settle that discussion asap. If the conclusion would be that we interpret the FV (1977) paper in such a way that this allows for the same spatial derivative to be calculated in two different ways for the same rhs, then an additional commit is required that would align marlpde with rhythmite in this respect. It would be nice if we could add that commit before this PR is merged. The FV paper is not an easy paper to interpret, though.

### CODE REVIEW

**Comment by EmiliaJarochowska** [comment]
Before getting to the discussion on F-V, I want to comment on this:
> However, b is set here to a default value of 5e-4, not to the [rhythmite value](https://github.com/cedrict/rhythmite/blob/6cd2e28f958857a3f0bf8a20320012af54277bfe/DiagenesisModel.py#L107). I.e. after merging with main and then running, marlpde will not yield oscillations within 250 ka.

The "default value" of 5e-4 is clearly assigned so as to compensate for the typo. It has no other motivation. If we do not use the typo and use the correct expression for the porosity diffusion coefficient, this value has no meaning. I believe we can leave it there though as the choice of `b` leading to oscillations is a matter of setting a parameter by the user.

**Comment by HannoSpreeuw** [comment]
Confusing indeed!

[`solver: str   = "scipy"` is actually not the solver but the `solve_ivp` module, as wrapped by py-pde](https://py-pde.readthedocs.io/en/latest/packages/pde.solvers.scipy.html#pde.solvers.scipy.ScipySolver.name).

What I am struggling with is that in `main` we currently have
```
    solver: str   = "explicit"
    scheme: str   = "rk"
```
Which will launch py-pde's native explicit solver with a Runge-Kutta scheme.    

However, `scheme` is not an argument of the [`ScipySolver`class](https://py-pde.readthedocs.io/en/latest/packages/pde.solvers.scipy.html#pde.solvers.scipy.ScipySolver). 
I.e. once you have chosen `solver: str   = "scipy"`, whatever you enter as `scheme` will not be propagated. Same for `retinfo` and `adaptive`. They have become meaningless in that case.

Somehwat related: it may be good to add a line to the `Solver` class, with `method = "LSODA"`, since that is now hardcoded in the [eq.solve call](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/blob/8b634699608ecc7348b41ecbf5279b5a733b3e29/marlpde/Evolve_scenario.py#L98). 
I can add this.

**Comment by EmiliaJarochowska** [comment]
I think what you proposed is indeed the best solution. But it would be useful to include a warning somewhere if anyone (including our future selves) tries to change the solver. E.g. I already encountered that confusion that changing the `adaptive` parameter didn't work and only after your explanation I understand why. 
Maybe it also needs an update of the README , because currently it says:

> After two minutes you should see plots similar to figure 3e from [L'Heureux (2018)](https://www.hindawi.com/journals/geofluids/2018/4968315/).

**Comment by HannoSpreeuw** [comment]
> I.e. once you have chosen `solver: str = "scipy"`, whatever you enter as `scheme` will not be propagated. Same for `retinfo` and `adaptive`. They have become meaningless in that case.

Sorry, not entirely correct, `retinfo: bool = True` is propagated in the solver call through `ret_info=kwargs["retinfo"]` since it is an argument of the [solver method of the pde base class](https://py-pde.readthedocs.io/en/latest/packages/pde.pdes.base.html#pde.pdes.base.PDEBase.solve).

**Comment by EmiliaJarochowska** [comment]
I ran after this change with the following options:
```
    solver: str   = "explicit"
    scheme: str   = "euler"
    adaptive: bool = False
```
and got
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pde/solvers/base.py", line 91, in from_name
    solver_class = cls._subclasses[name]
                   ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'LSODA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emilia/Documents/Documents - UU101746/GitHub/Integrating-diagenetic-equations-using-Python/marlpde/Evolve_scenario.py", line 143, in <module>
    integrate_equations(**all_kwargs)
  File "/Users/emilia/Documents/Documents - UU101746/GitHub/Integrating-diagenetic-equations-using-Python/marlpde/Evolve_scenario.py", line 96, in integrate_equations
    sol, info = eq.solve(state, t_range=End_time, dt=dt, \
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pde/pdes/base.py", line 582, in solve
    solver_obj = SolverBase.from_name(solver, pde=self, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pde/solvers/base.py", line 99, in from_name
    raise ValueError(
ValueError: Unknown solver method 'LSODA'. Registered solvers are 'AdaptiveSolverBase', 'explicit', 'explicit_mpi', 'implicit', 'scipy'
```

probably not relevant but I also set `b: quantity      = 1.066667 / u.kPa`

**Comment by HannoSpreeuw** [comment]
Yeah, `method='LSODA'` is not an explicit solver, more specifically, not provided by py-pde's native `'explicit'` solver method, you should choose `solver: str   = "scipy"` if you want to apply `'LSODA'`.

**Comment by EmiliaJarochowska** [comment]
But what should be set if I want to use `solver: str   = "explicit"`? Then `method` is not applicable.

**Comment by HannoSpreeuw** [comment]
Pls try again.

**Comment by HannoSpreeuw** [comment]
I found a more elegant solution on SO, using the [`post_init` method from Python dataclasses](https://stackoverflow.com/questions/67432117/if-else-in-python-dataclasses).

Btw, we already apply `post_init` in the [Map_Scenario method](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/blob/5fd917c800dcfcce8b56dcf6d25d6447be796598/marlpde/parameters.py#L126).

**Review by EmiliaJarochowska — APPROVED** [review]
Everything seems to work fine! Thank you :-)

**Comment by HannoSpreeuw** [comment]
Let me try to fix that: it would be nice if Figure 3 would be reproduced with our default settings.

**Comment by HannoSpreeuw** [comment]
> I found a more elegant solution on SO, using the [`post_init` method from Python dataclasses](https://stackoverflow.com/questions/67432117/if-else-in-python-dataclasses).
> 
> Btw, we already apply `post_init` in the [Map_Scenario method](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/blob/5fd917c800dcfcce8b56dcf6d25d6447be796598/marlpde/parameters.py#L126).

Let me just add that commit.

**Comment by HannoSpreeuw** [comment]
> Let me try to fix that: it would be nice if Figure 3 would be reproduced with our default settings.

O wait, that is perhaps as it should be, since we now have 0.8 as initial and surface default porosity.

**Comment by EmiliaJarochowska** [comment]
You changed the phis to 0.8 because we wanted potential users to find the conditions that lead the oscillations, as this is the point of interest of this model. Fig. 3 is more trivial, so to say. I guess if anyone uses this model, it is primarily to look at the oscillations. But it boils down to what the documentation would be. Have you thought of what the documentation will be? Our SMP has this field empty. I guess a simple documentation generated from your excellent docstrings with some preamble will be sufficient, as we can refer to the paper on the model itself.

**Comment by HannoSpreeuw** [comment]
Sounds like a plan!

**Pull request merged**
